SAMPLE_PRODUCTS = [
    {
        "asin": "TEST000001",
        "title": "モバイルバッテリー 10000mAh",
        "category": "家電",
        "original_price": 4980,
        "current_price": 2980,
        "discount_rate": 40,
        "rating": 4.4,
        "review_count": 1520,
        "is_prime": True,
    },
    {
        "asin": "TEST000002",
        "title": "ワイヤレスイヤホン Bluetooth対応",
        "category": "家電",
        "original_price": 6980,
        "current_price": 3480,
        "discount_rate": 50,
        "rating": 4.2,
        "review_count": 830,
        "is_prime": True,
    },
    {
        "asin": "TEST000003",
        "title": "ゲーミングマウス 軽量モデル",
        "category": "PC",
        "original_price": 5500,
        "current_price": 4400,
        "discount_rate": 20,
        "rating": 4.5,
        "review_count": 610,
        "is_prime": True,
    },
    {
        "asin": "TEST000004",
        "title": "キッチン収納ラック",
        "category": "ホーム",
        "original_price": 3800,
        "current_price": 1900,
        "discount_rate": 50,
        "rating": 4.0,
        "review_count": 210,
        "is_prime": False,
    },
    {
        "asin": "TEST000005",
        "title": "大容量ポータブル電源",
        "category": "家電",
        "original_price": 79800,
        "current_price": 47800,
        "discount_rate": 40,
        "rating": 4.6,
        "review_count": 320,
        "is_prime": True,
    },
    {
        "asin": "TEST000006",
        "title": "USB-C急速充電器 65W",
        "category": "PC",
        "original_price": 4990,
        "current_price": 2990,
        "discount_rate": 40,
        "rating": 4.7,
        "review_count": 2940,
        "is_prime": True,
    },
]